# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: beautiful_day.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'beautiful_day.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x62\x65\x61utiful_day.proto\x12\x12u2.beautifulday.v1\x1a\x1cgoogle/api/annotations.proto\" \n\x10\x45levationRequest\x12\x0c\n\x04mood\x18\x01 \x01(\t\"$\n\x11\x45levationResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"*\n\x17WithOrWithoutYouRequest\x12\x0f\n\x07partner\x18\x01 \x01(\t\"+\n\x18WithOrWithoutYouResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x97\x02\n\x0c\x42\x65\x61utifulDay\x12s\n\tElevation\x12$.u2.beautifulday.v1.ElevationRequest\x1a%.u2.beautifulday.v1.ElevationResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/u2/beautiful-day\x12\x91\x01\n\x10WithOrWithoutYou\x12+.u2.beautifulday.v1.WithOrWithoutYouRequest\x1a,.u2.beautifulday.v1.WithOrWithoutYouResponse\"\"\x82\xd3\xe4\x93\x02\x1c\"\x17/u2/with-or-without-you:\x01*b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'beautiful_day_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BEAUTIFULDAY'].methods_by_name['Elevation']._loaded_options = None
  _globals['_BEAUTIFULDAY'].methods_by_name['Elevation']._serialized_options = b'\202\323\344\223\002\023\022\021/u2/beautiful-day'
  _globals['_BEAUTIFULDAY'].methods_by_name['WithOrWithoutYou']._loaded_options = None
  _globals['_BEAUTIFULDAY'].methods_by_name['WithOrWithoutYou']._serialized_options = b'\202\323\344\223\002\034\"\027/u2/with-or-without-you:\001*'
  _globals['_ELEVATIONREQUEST']._serialized_start=73
  _globals['_ELEVATIONREQUEST']._serialized_end=105
  _globals['_ELEVATIONRESPONSE']._serialized_start=107
  _globals['_ELEVATIONRESPONSE']._serialized_end=143
  _globals['_WITHORWITHOUTYOUREQUEST']._serialized_start=145
  _globals['_WITHORWITHOUTYOUREQUEST']._serialized_end=187
  _globals['_WITHORWITHOUTYOURESPONSE']._serialized_start=189
  _globals['_WITHORWITHOUTYOURESPONSE']._serialized_end=232
  _globals['_BEAUTIFULDAY']._serialized_start=235
  _globals['_BEAUTIFULDAY']._serialized_end=514
# @@protoc_insertion_point(module_scope)
