# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import beautiful_day_pb2 as beautiful__day__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in beautiful_day_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BeautifulDayStub:
    """BeautifulDay demonstrates routes taken ENTIRELY from options. The pure-gRPC
    route stays /u2.beautifulday.v1.BeautifulDay/<Method>, but the
    google.api.http option defines a completely custom HTTP/REST path that is
    independent of the service and method names. Every custom route is under /u2.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Elevation = channel.unary_unary(
                '/u2.beautifulday.v1.BeautifulDay/Elevation',
                request_serializer=beautiful__day__pb2.ElevationRequest.SerializeToString,
                response_deserializer=beautiful__day__pb2.ElevationResponse.FromString,
                _registered_method=True)
        self.WithOrWithoutYou = channel.unary_unary(
                '/u2.beautifulday.v1.BeautifulDay/WithOrWithoutYou',
                request_serializer=beautiful__day__pb2.WithOrWithoutYouRequest.SerializeToString,
                response_deserializer=beautiful__day__pb2.WithOrWithoutYouResponse.FromString,
                _registered_method=True)


class BeautifulDayServicer:
    """BeautifulDay demonstrates routes taken ENTIRELY from options. The pure-gRPC
    route stays /u2.beautifulday.v1.BeautifulDay/<Method>, but the
    google.api.http option defines a completely custom HTTP/REST path that is
    independent of the service and method names. Every custom route is under /u2.
    """

    def Elevation(self, request, context):
        """gRPC route : /u2.beautifulday.v1.BeautifulDay/Elevation
        HTTP route : GET /u2/beautiful-day   (entirely from the option)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WithOrWithoutYou(self, request, context):
        """gRPC route : /u2.beautifulday.v1.BeautifulDay/WithOrWithoutYou
        HTTP route : POST /u2/with-or-without-you
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BeautifulDayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Elevation': grpc.unary_unary_rpc_method_handler(
                    servicer.Elevation,
                    request_deserializer=beautiful__day__pb2.ElevationRequest.FromString,
                    response_serializer=beautiful__day__pb2.ElevationResponse.SerializeToString,
            ),
            'WithOrWithoutYou': grpc.unary_unary_rpc_method_handler(
                    servicer.WithOrWithoutYou,
                    request_deserializer=beautiful__day__pb2.WithOrWithoutYouRequest.FromString,
                    response_serializer=beautiful__day__pb2.WithOrWithoutYouResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'u2.beautifulday.v1.BeautifulDay', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('u2.beautifulday.v1.BeautifulDay', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BeautifulDay:
    """BeautifulDay demonstrates routes taken ENTIRELY from options. The pure-gRPC
    route stays /u2.beautifulday.v1.BeautifulDay/<Method>, but the
    google.api.http option defines a completely custom HTTP/REST path that is
    independent of the service and method names. Every custom route is under /u2.
    """

    @staticmethod
    def Elevation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/u2.beautifulday.v1.BeautifulDay/Elevation',
            beautiful__day__pb2.ElevationRequest.SerializeToString,
            beautiful__day__pb2.ElevationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WithOrWithoutYou(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/u2.beautifulday.v1.BeautifulDay/WithOrWithoutYou',
            beautiful__day__pb2.WithOrWithoutYouRequest.SerializeToString,
            beautiful__day__pb2.WithOrWithoutYouResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
