# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import desire_pb2 as desire__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in desire_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DesireStub:
    """Desire is a second service in a different proto package, so its gRPC routes
    are prefixed /u2.desire.v1.Desire/<Method>. Its RPC routes are U2 songs.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Gloria = channel.unary_unary(
                '/u2.desire.v1.Desire/Gloria',
                request_serializer=desire__pb2.GloriaRequest.SerializeToString,
                response_deserializer=desire__pb2.GloriaResponse.FromString,
                _registered_method=True)
        self.Bad = channel.unary_unary(
                '/u2.desire.v1.Desire/Bad',
                request_serializer=desire__pb2.BadRequest.SerializeToString,
                response_deserializer=desire__pb2.BadResponse.FromString,
                _registered_method=True)


class DesireServicer:
    """Desire is a second service in a different proto package, so its gRPC routes
    are prefixed /u2.desire.v1.Desire/<Method>. Its RPC routes are U2 songs.
    """

    def Gloria(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Bad(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DesireServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Gloria': grpc.unary_unary_rpc_method_handler(
                    servicer.Gloria,
                    request_deserializer=desire__pb2.GloriaRequest.FromString,
                    response_serializer=desire__pb2.GloriaResponse.SerializeToString,
            ),
            'Bad': grpc.unary_unary_rpc_method_handler(
                    servicer.Bad,
                    request_deserializer=desire__pb2.BadRequest.FromString,
                    response_serializer=desire__pb2.BadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'u2.desire.v1.Desire', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('u2.desire.v1.Desire', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Desire:
    """Desire is a second service in a different proto package, so its gRPC routes
    are prefixed /u2.desire.v1.Desire/<Method>. Its RPC routes are U2 songs.
    """

    @staticmethod
    def Gloria(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/u2.desire.v1.Desire/Gloria',
            desire__pb2.GloriaRequest.SerializeToString,
            desire__pb2.GloriaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Bad(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/u2.desire.v1.Desire/Bad',
            desire__pb2.BadRequest.SerializeToString,
            desire__pb2.BadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
