# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: desire.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'desire.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64\x65sire.proto\x12\x0cu2.desire.v1\"\x1f\n\rGloriaRequest\x12\x0e\n\x06\x63\x61ller\x18\x01 \x01(\t\"!\n\x0eGloriaResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1a\n\nBadRequest\x12\x0c\n\x04mood\x18\x01 \x01(\t\"\x1e\n\x0b\x42\x61\x64Response\x12\x0f\n\x07message\x18\x01 \x01(\t2\x89\x01\n\x06\x44\x65sire\x12\x43\n\x06Gloria\x12\x1b.u2.desire.v1.GloriaRequest\x1a\x1c.u2.desire.v1.GloriaResponse\x12:\n\x03\x42\x61\x64\x12\x18.u2.desire.v1.BadRequest\x1a\x19.u2.desire.v1.BadResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'desire_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GLORIAREQUEST']._serialized_start=30
  _globals['_GLORIAREQUEST']._serialized_end=61
  _globals['_GLORIARESPONSE']._serialized_start=63
  _globals['_GLORIARESPONSE']._serialized_end=96
  _globals['_BADREQUEST']._serialized_start=98
  _globals['_BADREQUEST']._serialized_end=124
  _globals['_BADRESPONSE']._serialized_start=126
  _globals['_BADRESPONSE']._serialized_end=156
  _globals['_DESIRE']._serialized_start=159
  _globals['_DESIRE']._serialized_end=296
# @@protoc_insertion_point(module_scope)
