# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import vertigo_pb2 as vertigo__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vertigo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VertigoStub:
    """Vertigo is a service whose RPC routes are named after U2 songs.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.One = channel.unary_unary(
                '/u2.vertigo.v1.Vertigo/One',
                request_serializer=vertigo__pb2.OneRequest.SerializeToString,
                response_deserializer=vertigo__pb2.OneResponse.FromString,
                _registered_method=True)
        self.Pride = channel.unary_unary(
                '/u2.vertigo.v1.Vertigo/Pride',
                request_serializer=vertigo__pb2.PrideRequest.SerializeToString,
                response_deserializer=vertigo__pb2.PrideResponse.FromString,
                _registered_method=True)


class VertigoServicer:
    """Vertigo is a service whose RPC routes are named after U2 songs.
    """

    def One(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Pride(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VertigoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'One': grpc.unary_unary_rpc_method_handler(
                    servicer.One,
                    request_deserializer=vertigo__pb2.OneRequest.FromString,
                    response_serializer=vertigo__pb2.OneResponse.SerializeToString,
            ),
            'Pride': grpc.unary_unary_rpc_method_handler(
                    servicer.Pride,
                    request_deserializer=vertigo__pb2.PrideRequest.FromString,
                    response_serializer=vertigo__pb2.PrideResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'u2.vertigo.v1.Vertigo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('u2.vertigo.v1.Vertigo', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Vertigo:
    """Vertigo is a service whose RPC routes are named after U2 songs.
    """

    @staticmethod
    def One(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/u2.vertigo.v1.Vertigo/One',
            vertigo__pb2.OneRequest.SerializeToString,
            vertigo__pb2.OneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Pride(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/u2.vertigo.v1.Vertigo/Pride',
            vertigo__pb2.PrideRequest.SerializeToString,
            vertigo__pb2.PrideResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
