# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vertigo.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'vertigo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rvertigo.proto\x12\ru2.vertigo.v1\"\x1c\n\nOneRequest\x12\x0e\n\x06singer\x18\x01 \x01(\t\"\x1e\n\x0bOneResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1c\n\x0cPrideRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\" \n\rPrideResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x8b\x01\n\x07Vertigo\x12<\n\x03One\x12\x19.u2.vertigo.v1.OneRequest\x1a\x1a.u2.vertigo.v1.OneResponse\x12\x42\n\x05Pride\x12\x1b.u2.vertigo.v1.PrideRequest\x1a\x1c.u2.vertigo.v1.PrideResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vertigo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ONEREQUEST']._serialized_start=32
  _globals['_ONEREQUEST']._serialized_end=60
  _globals['_ONERESPONSE']._serialized_start=62
  _globals['_ONERESPONSE']._serialized_end=92
  _globals['_PRIDEREQUEST']._serialized_start=94
  _globals['_PRIDEREQUEST']._serialized_end=122
  _globals['_PRIDERESPONSE']._serialized_start=124
  _globals['_PRIDERESPONSE']._serialized_end=156
  _globals['_VERTIGO']._serialized_start=159
  _globals['_VERTIGO']._serialized_end=298
# @@protoc_insertion_point(module_scope)
